[package]
name = "subkey"
version = "0.1.0"
authors = ["Gav <gavin@parity.io>"]

[dependencies]
ed25519 = { version = "*", path = "../substrate/ed25519" }
substrate-primitives = { version = "*", path = "../substrate/primitives" }
